### ISSUE TITLE
Add Social media icons to the select boxes on the left hand side of the UI

### ISSUE THREAD

**Issue by IshaanShettigar** [vivek-698/Chaos-to-Clarity#2]
![image](https://github.com/vivek-698/Chaos-to-Clarity/assets/77607172/41ab2eae-0ef5-4667-999d-21dc1aa0285f)

Add the icons next to the text or do whatever, just make it look nice.

**Comment by Utkarsh3010** [comment]
I can Do it for You . But it seems the app is not running on my machine can you elaborate more like how can I run it.
I have Installed the flask as you have suggested in Readme

**Comment by IshaanShettigar** [comment]
Thats awesome! Just run `python3 flask-app.py ` in your terminal, it should start running the project in localhost, and a message will come on the terminal telling you which port it's being run on.
If that doesn't work just use the live server option in VS code (Since you're just editing the UI, you don't need to run the flask app as such, you can get away with just using the live server). You can find the HTML files in the templates folder. The CSS file is in the statics folder labelled as `styles.css`.

**Comment by IshaanShettigar** [comment]
@caelanq04 opened a PR and we merged. I fixed the `<img src="..."/>` to match what is expected by Flask.

**Comment by caelanq04** [comment]
@IshaanShettigar Thanks for the comment, this was my first time using flask so will know for the future what to do with the src
